import type { InferGetServerSidePropsType } from "next";
import { type NextPage } from "next";
import Head from "next/head";
import { FC, useState } from "react";
import { Card } from "../components/Card";
import { CardPost } from "../components/CardPost";
import Navbar from "../components/Navbar";
import { RightSideBar } from "../components/RightSidebar";
import { LeftSidebar } from "../components/Sidebar";

export const getServerSideProps = async () => {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
};

const Home: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ data }) => {
  const [navbarIsOpen, setNavbarIsOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Sciaa - SoCial App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        title="Sciaa"
        isOpen={navbarIsOpen}
        onToggle={() => setNavbarIsOpen((prevState) => !prevState)}
      />
      <main className="container flex min-h-screen  gap-3  ">
        <LeftSidebar />
        <div className="overflow-scroll">
          <div className="flex flex-col gap-5">
            {data.map((item) => {
              return (
                <Card
                  title={item.title}
                  hashtags={["hello", "world", "programming", "javascript"]}
                  description={item.body}
                  imgUrl="https://via.placeholder.com/600.png"
                  key={item.id}
                />
              );
            })}
          </div>
        </div>
        <RightSideBar />
      </main>
    </>
  );
};
export default Home;
