import type { InferGetServerSidePropsType } from "next";
import { type NextPage } from "next";
import Head from "next/head";
import { FC, useState } from "react";
import { Card } from "../components/Card";
import { CardPost } from "../components/CardPost";
import Navbar from "../components/Navbar";
import { RightSideBar } from "../components/RightSidebar";
import { LeftSidebar } from "../components/Sidebar";

export const getServerSideProps = async () => {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
};

const Home: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ data }) => {
  const [navbarIsOpen, setNavbarIsOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Sciaa - SoCial App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen min-h-screen flex-col overflow-hidden">
        <Navbar
          title="Sciaa"
          isOpen={navbarIsOpen}
          onToggle={() => setNavbarIsOpen((prevState) => !prevState)}
        />
        <div className="flex flex-1 flex-col gap-8 overflow-scroll sm:flex-row">
          <main className="mx-auto w-full flex-1 overflow-scroll">
            {data.map((item) => {
              return (
                <Card
                  title={item.title}
                  hashtags={["Hello", "Programming", "Javascript"]}
                  description={item.body}
                  imgUrl={"https://via.placeholder.com/600.png"}
                  key={item.id}
                />
              );
            })}
          </main>

          <LeftSidebar />
          <RightSideBar />
        </div>
      </div>
    </>
  );
};
export default Home;
